services:
    "gitlab.com": "gitlab:gitlab.com/quick-development/frontend/quick"

gui:
  # Status panel view.
  # One of 'dashboard' (default) | 'allBranchesLog'
  statusPanelView: allBranchesLog
  showFileTree: true
  # One of: 'normal' (default) | 'half' | 'full'
  windowSize: normal
  expandFocusedSidePanel: true
  sidePanelWidth: 0.3 # gives you more space to show things side-by-side
  nerdFontsVersion: "3"
  border: 'rounded'
  branchColors:
    'feature': '#67e92f' # apply color for branches beginning with 'feature/'
    'bugfix':  '#ffc30c'
    'fix':  '#ffc30c'
    'hotfix': '#f71e1e'
    'main': '#169bff'
    'develop': '#169bff'
  theme:
    activeBorderColor:
      - green
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
      - bold
    selectedRangeBgColor:
      - green
      - bold
    unstagedChangesColor:
      - red


git:
  branchPrefix: "feature/ODP-"
  branchLogCmd: "git log --graph --color=always  --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold blue)— %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative "
  paging:
    colorArg: always
    pager: diff-so-fancy
    
  commitPrefixes:
    quick: # This is repository folder name
      pattern: "(\\w+)/(\\w+-\\d+)_(.*)"
      replace: '$1($2): $3'
      
os:
  edit: 'code {{filename}}'
  editAtLine: 'code --goto {{filename}}:{{line}}'
  editAtLineAndWait: 'code --goto {{filename}}:{{line}}'
  editInTerminal: false
  openDirInEditor: 'code --goto {{dir}}'
  open: 'code --goto {{filename}}'

update:
  # One of: 'prompt' (default) | 'background' | 'never'
  method: prompt

disableStartupPopups: false

notARepository: skip
