services:
    "gitlab.com": "gitlab:gitlab.com/quick-development/frontend/quick"

gui:
  sidePanelWidth: 0.2 # gives you more space to show things side-by-side
  nerdFontsVersion: "3"
  branchColors:
    'feature': '#67e92f' # apply color for branches beginning with 'feature/'
    'bugfix':  '#ffc30c'
    'fix':  '#ffc30c'
    'hotfix': '#f71e1e'
    'main': '#169bff'
    'develop': '#169bff'


git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    
  commitPrefixes:
    quick: # This is repository folder name
      pattern: "\\/(ODP-\\d+)_.*"
      replace: '($1): '
      
os:
  edit: 'code {{filename}}'
  editAtLine: 'code --goto {{filename}}:{{line}}'
  editAtLineAndWait: 'code --goto {{filename}}:{{line}}'
  editInTerminal: false
  openDirInEditor: 'code {{dir}}'


disableStartupPopups: false

notARepository: skip
